# Generated by Django 5.0 on 2023-12-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='CREATED', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=50)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=60)),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['id'], name='orders_id_ddf884_idx')],
            },
        ),
    ]
