# Generated by Django 5.0 on 2023-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='NA')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=50)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=60)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['id'], name='products_id_5ad420_idx')],
            },
        ),
    ]
