# Generated by Django 5.0 on 2023-12-18 15:31

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('password', models.CharField(default='', max_length=100)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'SUPERADMIN'), ('ENDUSER', 'ENDUSER')], default='ENDUSER', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('custom_permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=50)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=60)),
            ],
            options={
                'db_table': 'usermaster',
                'indexes': [models.Index(fields=['mobile'], name='usermaster_mobile_4fe94f_idx')],
            },
        ),
    ]
